labels = ['gender', 'parental level of education', 'test preparation course', 'math score', 'reading score', 'writing score']
data = [ 
 ['female', "bachelor's degree", 'none', '72', '72', '74'], 
 ['female', 'some college', 'completed', '69', '90', '88'], 
 ['female', "master's degree", 'none', '90', '95', '93'], 
 ['male', "associate's degree", 'none', '47', '57', '44'], 
 ['male', 'some college', 'none', '76', '78', '75'], 
 ['female', "associate's degree", 'none', '71', '83', '78'], 
 ['female', 'some college', 'completed', '88', '95', '92'], 
 ['male', 'some college', 'none', '40', '43', '39'], 
 ['male', 'high school', 'completed', '64', '64', '67'], 
 ['female', 'high school', 'none', '38', '60', '50'], 
 ['male', "associate's degree", 'none', '58', '54', '52'], 
 ['male', "associate's degree", 'none', '40', '52', '43'], 
 ['female', 'high school', 'none', '65', '81', '73'], 
 ['male', 'some college', 'completed', '78', '72', '70'], 
 ['female', "master's degree", 'none', '50', '53', '58'], 
 ['female', 'some high school', 'none', '69', '75', '78'], 
 ['male', 'high school', 'none', '88', '89', '86'], 
 ['female', 'some high school', 'none', '18', '32', '28'], 
 ['male', "master's degree", 'completed', '46', '42', '46'], 
 ['female', "associate's degree", 'none', '54', '58', '61'], 
 ['male', 'high school', 'none', '66', '69', '63'], 
 ['female', 'some college', 'completed', '65', '75', '70'], 
 ['male', 'some college', 'none', '44', '54', '53'], 
 ['female', 'some high school', 'none', '69', '73', '73'], 
 ['male', "bachelor's degree", 'completed', '74', '71', '80'], 
 ['male', "master's degree", 'none', '73', '74', '72'], 
 ['male', 'some college', 'none', '69', '54', '55'], 
 ['female', "bachelor's degree", 'none', '67', '69', '75'], 
 ['male', 'high school', 'none', '70', '70', '65'], 
 ['female', "master's degree", 'none', '62', '70', '75'], 
 ['female', 'some college', 'none', '69', '74', '74'], 
 ['female', 'some college', 'none', '63', '65', '61'], 
 ['female', "master's degree", 'none', '56', '72', '65'], 
 ['male', 'some college', 'none', '40', '42', '38'], 
 ['male', 'some college', 'none', '97', '87', '82'], 
 ['male', "associate's degree", 'completed', '81', '81', '79'], 
 ['female', "associate's degree", 'none', '74', '81', '83'], 
 ['female', 'some high school', 'none', '50', '64', '59'], 
 ['female', "associate's degree", 'completed', '75', '90', '88'], 
]
